#!/usr/bin/env python3
"""Generate N64Recomp reference-symbol TOMLs from the decomp's recomp ELF.

Patches are C compiled to MIPS that override or call game functions by name. To recompile
patches.elf, N64Recomp needs to know where those game symbols live, which it reads from
`func_reference_syms_file` and `data_reference_syms_files` in patches.toml. Nothing generates
those, so this does.

The schema is the one N64Recomp::Context::from_symbol_file parses:

    [[section]]
    name = ".text"
    rom  = 0x1000        # file offset of the section
    vram = 0x80000400    # virtual address
    size = 0x1234
    functions = [ { name = "func", vram = 0x80000400, size = 0x40 }, ... ]

Data sections use the same section blocks with an empty function list; the data symbols
themselves are what the recompiler resolves against.

Run it through WSL, where the MIPS binutils live:

    wsl -d Ubuntu -- python3 tools/gen_reference_syms.py \\
        elf/recomp.elf syms/beetleadventurerac.us.syms.toml syms/beetleadventurerac.us.datasyms.toml
"""

import re
import subprocess
import sys

READELF = "mips-linux-gnu-readelf"


def run(*args):
    out = subprocess.run(args, capture_output=True, text=True, check=True)
    return out.stdout


def parse_sections(elf):
    """Return {index: dict(name, addr, off, size, exec)} for allocated sections."""
    sections = {}
    # readelf -SW lines look like:
    #   [ 6] .text  PROGBITS  80000400 001000 0334e0 00  AX  0   0 16
    line_re = re.compile(
        r"^\s*\[\s*(\d+)\]\s+(\S+)\s+(\S+)\s+([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+\S+\s+(\S*)"
    )
    for line in run(READELF, "-SW", elf).splitlines():
        m = line_re.match(line)
        if not m:
            continue
        idx, name, kind, addr, off, size, flags = m.groups()
        if "A" not in flags:          # not allocated at runtime -> not interesting
            continue
        if kind in ("NOBITS",):       # .bss has no file bytes but still holds data symbols
            pass
        sections[int(idx)] = {
            "name": name,
            "addr": int(addr, 16),
            "off": int(off, 16),
            "size": int(size, 16),
            "exec": "X" in flags,
        }
    return sections


def parse_symbols(elf):
    """Return (funcs, objects) as lists of dict(name, value, size, shndx)."""
    funcs, objects = [], []
    # readelf -sW lines:
    #   123: 80000400   64 FUNC    GLOBAL DEFAULT    6 some_func
    line_re = re.compile(
        r"^\s*\d+:\s+([0-9a-fA-F]+)\s+(\d+)\s+(FUNC|OBJECT)\s+\S+\s+\S+\s+(\S+)\s+(\S+)"
    )
    for line in run(READELF, "-sW", elf).splitlines():
        m = line_re.match(line)
        if not m:
            continue
        value, size, kind, shndx, name = m.groups()
        if shndx in ("UND", "ABS", "COM"):
            continue
        if name.endswith(".NON_MATCHING"):   # splat emits paired OBJECT aliases; skip them
            continue
        entry = {
            "name": name,
            "value": int(value, 16),
            "size": int(size),
            "shndx": int(shndx),
        }
        (funcs if kind == "FUNC" else objects).append(entry)
    return funcs, objects


def emit(path, sections, symbols_by_section, want_exec):
    """Write one reference-symbol TOML.

    The two files use different shapes, which is easy to miss: executable sections carry
    `functions = [{ name, vram, size }]` and data sections carry `symbols = [{ name, vram }]`.
    Size is required for functions (the recompiler needs the boundary) and absent for data, so
    zero-size symbols are only dropped from the function file.
    """
    key = "functions" if want_exec else "symbols"
    n_sections = n_syms = 0
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by tools/gen_reference_syms.py — do not edit by hand.\n")
        f.write("# Reference symbols so N64Recomp can resolve patch relocations against the game.\n\n")
        for idx, sec in sorted(sections.items()):
            if sec["exec"] != want_exec:
                continue
            syms = symbols_by_section.get(idx, [])
            if not syms and not want_exec:
                continue
            n_sections += 1
            f.write("[[section]]\n")
            f.write(f'name = "{sec["name"]}"\n')
            f.write(f'rom  = 0x{sec["off"]:X}\n')
            f.write(f'vram = 0x{sec["addr"]:X}\n')
            f.write(f'size = 0x{sec["size"]:X}\n')
            f.write(f"{key} = [\n")
            for s in sorted(syms, key=lambda s: s["value"]):
                if want_exec:
                    if s["size"] == 0:
                        continue      # no boundary -> the recompiler cannot use it
                    f.write(f'    {{ name = "{s["name"]}", vram = 0x{s["value"]:X}, size = 0x{s["size"]:X} }},\n')
                else:
                    f.write(f'    {{ name = "{s["name"]}", vram = 0x{s["value"]:X} }},\n')
                n_syms += 1
            f.write("]\n\n")
    return n_sections, n_syms


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 1
    elf, func_out, data_out = sys.argv[1:4]

    sections = parse_sections(elf)
    funcs, objects = parse_symbols(elf)

    by_sec_f, by_sec_d = {}, {}
    for s in funcs:
        by_sec_f.setdefault(s["shndx"], []).append(s)
    for s in objects:
        by_sec_d.setdefault(s["shndx"], []).append(s)

    fs, fn = emit(func_out, sections, by_sec_f, want_exec=True)
    ds, dn = emit(data_out, sections, by_sec_d, want_exec=False)

    print(f"{func_out}: {fs} executable sections, {fn} functions")
    print(f"{data_out}: {ds} data sections, {dn} objects")
    return 0


if __name__ == "__main__":
    sys.exit(main())
